version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: MyShop
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
  myrestapp:
    container_name: myrestapp
    image: myrestapp
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MyShop?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql





